package providers

import (
	"path/filepath"
	"strings"
)

type AppDataProvider struct{}

func (p *AppDataProvider) ID() string { return "appdata_cache" }
func (p *AppDataProvider) Name() string { return "AppData Cache" }

func (p *AppDataProvider) Detect(path string, isDir bool) (bool, ScanDirective) {
	if !isDir {
		return false, ContinueTraversal
	}
	normalized := strings.ToLower(filepath.ToSlash(path))
	
	// Flag known massive cache directories inside AppData
	if strings.Contains(normalized, "appdata/local/spotify/storage") ||
	   strings.Contains(normalized, "appdata/roaming/discord/cache") ||
	   strings.Contains(normalized, "appdata/local/google/chrome/user data/default/cache") ||
	   strings.Contains(normalized, "appdata/local/bravesoftware/brave-browser/user data/default/cache") {
		return true, StopTraversal
	}
	return false, ContinueTraversal
}

func (p *AppDataProvider) Analyze(path string) (AnalysisResult, error) {
	return AnalysisResult{
		Risk:    "Safe",
		Context: "Temporary application cache. Safe to delete, will be regenerated by the app when needed.",
	}, nil
}

func (p *AppDataProvider) GetCleanupActions(path string) []Action {
	return []Action{
		{
			Name:    "Delete Directory",
			Command: "Remove-Item -Recurse -Force '" + path + "'",
		},
	}
}
